/*
DECLARE
    V_MAX_DEPTNO NUMBER(4,0);
BEGIN
    SELECT d.DEPARTMENT_ID
    INTO V_MAX_DEPTNO
    FROM OEHR_DEPARTMENTS d
    WHERE d.DEPARTMENT_ID >= (SELECT MAX(d1.DEPARTMENT_ID) FROM OEHR_DEPARTMENTS d1);
    dbms_output.put_line(V_MAX_DEPTNO);
END;
*/

DECLARE
    V_MAX_DEPTNO NUMBER(4,0);
BEGIN
    SELECT d.DEPARTMENT_ID
    INTO V_MAX_DEPTNO
    FROM OEHR_DEPARTMENTS d
    WHERE d.DEPARTMENT_ID >= (SELECT MAX(d1.DEPARTMENT_ID) FROM OEHR_DEPARTMENTS d1);
    dbms_output.put_line(V_MAX_DEPTNO);
END;
