DROP TABLE TELEFONE_CLIENTE;
DROP TABLE ENDERECO_CLIENTE;

DROP TABLE TELEFONE_FUNCIONARIO;
DROP TABLE DEPENDENTE_FUNCIONARIO;

DROP TABLE FUNCIONARIO_POR_FILIAL;
DROP TABLE RECLAMACAO_CLIENTE_FILIAL;

DROP TABLE CLIENTE;
DROP TABLE FILIAL CASCADE CONSTRAINT;
DROP TABLE FUNCIONARIO CASCADE CONSTRAINT;
