DROP TABLE ITEM_DE_COMPRA;
DROP TABLE ORDEM_DE_COMPRA;

DROP TABLE PRODUTO_POR_FILIAL;
DROP TABLE MARCA_PRODUTO;
DROP TABLE CATEGORIA_PRODUTO;
DROP TABLE PRODUTO;

DROP TABLE PLANO_DE_MANUTENCAO;
DROP TABLE EQUIPAMENTO;
DROP TABLE CAIXA;

DROP TABLE TELEFONE_CLIENTE;
DROP TABLE ENDERECO_CLIENTE;

DROP TABLE TELEFONE_FUNCIONARIO;
DROP TABLE DEPENDENTE_FUNCIONARIO;

DROP TABLE FUNCIONARIO_POR_FILIAL;
DROP TABLE RECLAMACAO_CLIENTE_FILIAL;

DROP TABLE CLIENTE;
DROP TABLE FILIAL CASCADE CONSTRAINT;
DROP TABLE FUNCIONARIO CASCADE CONSTRAINT;

DROP TABLE SOLICITACAO;
