DROP TABLE SOLICITACAO;
DROP TABLE ITEM_DE_COMPRA;
DROP TABLE NOTA_FISCAL;

DROP TABLE ORDEM_DE_COMPRA;
DROP TABLE PLANO_DE_MANUTENCAO;
DROP TABLE EQUIPAMENTO;
DROP TABLE CAIXA;

DROP TABLE RECLAMACAO_CLIENTE_FILIAL;

DROP TABLE TELEFONE_FORNECEDORES;
DROP TABLE FORNECEDORES;

DROP TABLE PRODUTO;
DROP TABLE MARCA_PRODUTO;
DROP TABLE CATEGORIA_PRODUTO;

DROP TABLE TELEFONE_CLIENTE;
DROP TABLE CLIENTE;
DROP TABLE DEPENDENTE_FUNCIONARIO;
DROP TABLE TELEFONE_FUNCIONARIO;
DROP TABLE FILIAL CASCADE CONSTRAINT;
DROP TABLE FUNCIONARIO CASCADE CONSTRAINT;
